#!/usr/bin/env python3
"""Build the Quiz reel dataset from the app's grammar question bank.

Reads ../data/grammar.ts (GrammarQuestion[]), picks 10 short N5/N4 items,
writes src/quiz/data.ts, synthesizes the correct-sentence audio via Edge TTS,
and generates the countdown tick sound (numpy).

Idempotent: audio/timings are skipped when the timings JSON already exists;
data.ts is regenerated deterministically each run.
"""
import asyncio
import json
import re
import subprocess
import tempfile
from pathlib import Path

import edge_tts
import numpy as np

ROOT = Path(__file__).resolve().parent.parent
BANK = ROOT.parent / "data" / "grammar.ts"
OUT = ROOT / "public" / "quiz"
TIMINGS_DIR = ROOT / "src" / "quiz" / "timings"
DATA_TS = ROOT / "src" / "quiz" / "data.ts"
VOICE = "ja-JP-NanamiNeural"
RATE = "-10%"
SR = 44100
PICK = 32


def probe_duration(path: Path) -> float:
    r = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "csv=p=0", str(path)],
        capture_output=True, text=True,
    )
    return float(r.stdout.strip())


async def synth(text: str, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    await edge_tts.Communicate(text, VOICE, rate=RATE).save(str(path))


def parse_bank() -> list[dict]:
    src = BANK.read_text()
    blocks = re.findall(
        r"\{\s*id:\s*'([^']+)',\s*sentence:\s*'([^']+)',\s*options:\s*\[([^\]]+)\],\s*"
        r"answer:\s*'([^']+)',\s*explanation:\s*'((?:[^'\\]|\\.)*)',\s*"
        r"point:\s*'([^']+)',\s*level:\s*'([^']+)'",
        src,
    )
    items = []
    for qid, sentence, opts_raw, answer, explanation, point, level in blocks:
        options = re.findall(r"'([^']*)'", opts_raw)
        items.append({
            "qid": qid, "sentence": sentence, "options": options,
            "answer": answer,
            "explanation": explanation.replace("\\n", "\n").split("\n")[0],
            "point": point, "level": level,
        })
    return items


def pick_items(items: list[dict]) -> list[dict]:
    good = [
        it for it in items
        if it["level"] in ("N5", "N4")
        and "___" in it["sentence"]
        and len(it["sentence"]) <= 20
        and len(it["options"]) == 4
        and all(len(o) <= 6 for o in it["options"])
        and it["answer"] in it["options"]
    ]
    good.sort(key=lambda it: it["qid"])
    return good[:PICK]


def gen_tick():
    """Three short beeps, one per countdown second."""
    out = OUT / "tick.mp3"
    if out.exists():
        print("[quiz] tick.mp3 exists, skip")
        return
    beep_len, gap_len = 0.09, 0.91
    seg = []
    for i in range(3):
        t = np.linspace(0, beep_len, int(SR * beep_len), endpoint=False)
        freq = 880 if i < 2 else 1320  # last beep higher — "time's up"
        beep = np.sin(2 * np.pi * freq * t) * np.exp(-t * 18) * 0.5
        seg.append(beep)
        seg.append(np.zeros(int(SR * gap_len)))
    track = np.concatenate(seg)
    track_16 = (track * 32767).astype(np.int16)
    import wave
    with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as f:
        w = wave.open(f.name, "w")
        w.setnchannels(1); w.setsampwidth(2); w.setframerate(SR)
        w.writeframes(track_16.tobytes()); w.close()
        out.parent.mkdir(parents=True, exist_ok=True)
        subprocess.run(["ffmpeg", "-y", "-i", f.name, "-b:a", "128k", str(out)],
                       capture_output=True, check=True)
    print(f"[quiz] tick.mp3 written")


def write_data_ts(picked: list[dict]):
    lines = [
        "// AUTO-GENERATED by scripts/gen_quiz_data.py — do not edit by hand.",
        "// Source: ../../data/grammar.ts (app grammar question bank).",
        "export type QuizTimings = { answer: number };",
        "",
        "export type QuizItem = {",
        "  id: string;",
        "  sentence: string;",
        "  options: string[];",
        "  answer: string;",
        "  answerIndex: number;",
        "  explanation: string;",
        "  point: string;",
        "  level: string;",
        "  timings?: QuizTimings;",
        "};",
        "",
    ]
    for i in range(len(picked)):
        lines.append(f'import t{i+1:02d} from "./timings/{i+1:02d}.json";')
    lines.append("")
    lines.append("export const quizItems: QuizItem[] = [")
    for i, it in enumerate(picked):
        nid = f"{i+1:02d}"
        opts = ", ".join(json.dumps(o, ensure_ascii=False) for o in it["options"])
        lines.append("  {")
        lines.append(f'    id: "{nid}",')
        lines.append(f'    sentence: {json.dumps(it["sentence"], ensure_ascii=False)},')
        lines.append(f"    options: [{opts}],")
        lines.append(f'    answer: {json.dumps(it["answer"], ensure_ascii=False)},')
        lines.append(f'    answerIndex: {it["options"].index(it["answer"])},')
        lines.append(f'    explanation: {json.dumps(it["explanation"], ensure_ascii=False)},')
        lines.append(f'    point: {json.dumps(it["point"], ensure_ascii=False)},')
        lines.append(f'    level: {json.dumps(it["level"], ensure_ascii=False)},')
        lines.append(f"    timings: t{nid},")
        lines.append("  },")
    lines.append("];")
    DATA_TS.parent.mkdir(parents=True, exist_ok=True)
    DATA_TS.write_text("\n".join(lines) + "\n")
    print(f"[quiz] data.ts written ({len(picked)} items)")


async def main():
    picked = pick_items(parse_bank())
    assert len(picked) == PICK, f"only {len(picked)} usable items, need {PICK}"
    TIMINGS_DIR.mkdir(parents=True, exist_ok=True)
    for i, it in enumerate(picked):
        nid = f"{i+1:02d}"
        tj = TIMINGS_DIR / f"{nid}.json"
        if tj.exists():
            print(f"[quiz {nid}] timings exist, skip")
            continue
        full = it["sentence"].replace("___", it["answer"])
        await synth(full, OUT / nid / "answer.mp3")
        tj.write_text(json.dumps({"answer": probe_duration(OUT / nid / "answer.mp3")}, indent=2))
        print(f"[quiz {nid}] {full}")
    gen_tick()
    write_data_ts(picked)


if __name__ == "__main__":
    asyncio.run(main())
