// AUTO-GENERATED by scripts/gen_quiz_data.py — do not edit by hand.
// Source: ../../data/grammar.ts (app grammar question bank).
export type QuizTimings = { answer: number };

export type QuizItem = {
  id: string;
  sentence: string;
  options: string[];
  answer: string;
  answerIndex: number;
  explanation: string;
  point: string;
  level: string;
  timings?: QuizTimings;
};

import t01 from "./timings/01.json";
import t02 from "./timings/02.json";
import t03 from "./timings/03.json";
import t04 from "./timings/04.json";
import t05 from "./timings/05.json";
import t06 from "./timings/06.json";
import t07 from "./timings/07.json";
import t08 from "./timings/08.json";
import t09 from "./timings/09.json";
import t10 from "./timings/10.json";
import t11 from "./timings/11.json";
import t12 from "./timings/12.json";
import t13 from "./timings/13.json";
import t14 from "./timings/14.json";
import t15 from "./timings/15.json";
import t16 from "./timings/16.json";
import t17 from "./timings/17.json";
import t18 from "./timings/18.json";
import t19 from "./timings/19.json";
import t20 from "./timings/20.json";
import t21 from "./timings/21.json";
import t22 from "./timings/22.json";
import t23 from "./timings/23.json";
import t24 from "./timings/24.json";
import t25 from "./timings/25.json";
import t26 from "./timings/26.json";
import t27 from "./timings/27.json";
import t28 from "./timings/28.json";
import t29 from "./timings/29.json";
import t30 from "./timings/30.json";
import t31 from "./timings/31.json";
import t32 from "./timings/32.json";

export const quizItems: QuizItem[] = [
  {
    id: "01",
    sentence: "わたし___がくせいです。",
    options: ["は", "が", "を", "に"],
    answer: "は",
    answerIndex: 0,
    explanation: "「は」是主題助詞，用來提示句子的主題。",
    point: "は（主題助詞）",
    level: "N5",
    timings: t01,
  },
  {
    id: "02",
    sentence: "あそこに ねこ___います。",
    options: ["は", "が", "を", "で"],
    answer: "が",
    answerIndex: 1,
    explanation: "「が」用來強調主語，特別是描述存在（います／あります）時使用。",
    point: "が（主語助詞）",
    level: "N5",
    timings: t02,
  },
  {
    id: "03",
    sentence: "まいあさ コーヒー___のみます。",
    options: ["は", "が", "を", "に"],
    answer: "を",
    answerIndex: 2,
    explanation: "「を」是受詞助詞，接在動作的對象（受詞）後面。",
    point: "を（受詞助詞）",
    level: "N5",
    timings: t03,
  },
  {
    id: "04",
    sentence: "えいご___べんきょうしています。",
    options: ["は", "が", "を", "で"],
    answer: "を",
    answerIndex: 2,
    explanation: "「勉強する」是他動詞，學習的科目要用「を」。",
    point: "を（受詞助詞）",
    level: "N5",
    timings: t04,
  },
  {
    id: "05",
    sentence: "がっこう___いきます。",
    options: ["を", "が", "に", "で"],
    answer: "に",
    answerIndex: 2,
    explanation: "「に」表示移動的目的地。",
    point: "に（方向・目的地）",
    level: "N5",
    timings: t05,
  },
  {
    id: "06",
    sentence: "つくえの うえ___ほんが あります。",
    options: ["に", "で", "を", "が"],
    answer: "に",
    answerIndex: 0,
    explanation: "「に」也表示物品存在的位置。",
    point: "に（存在場所）",
    level: "N5",
    timings: t06,
  },
  {
    id: "07",
    sentence: "としょかん___べんきょうします。",
    options: ["に", "で", "を", "が"],
    answer: "で",
    answerIndex: 1,
    explanation: "「で」表示動作發生的場所。",
    point: "で（動作場所）",
    level: "N5",
    timings: t07,
  },
  {
    id: "08",
    sentence: "でんしゃ___かいしゃに いきます。",
    options: ["に", "で", "を", "は"],
    answer: "で",
    answerIndex: 1,
    explanation: "「で」也表示使用的交通工具或手段。",
    point: "で（手段・方法）",
    level: "N5",
    timings: t08,
  },
  {
    id: "09",
    sentence: "きのう えいが を ___。",
    options: ["みます", "みました", "みて", "みない"],
    answer: "みました",
    answerIndex: 1,
    explanation: "「〜ました」是禮貌形過去式。",
    point: "〜ました（過去形）",
    level: "N5",
    timings: t09,
  },
  {
    id: "10",
    sentence: "わたしは さかな___たべません。",
    options: ["を", "が", "は", "に"],
    answer: "は",
    answerIndex: 2,
    explanation: "否定句中，「〜は〜ません」的「は」有對比的語感，",
    point: "〜は〜ません（對比否定）",
    level: "N5",
    timings: t10,
  },
  {
    id: "11",
    sentence: "あした がっこうに ___。",
    options: ["いきます", "いきません", "いきました", "いって"],
    answer: "いきません",
    answerIndex: 1,
    explanation: "「〜ません」是否定形，表示不會做某事。",
    point: "〜ません（否定形）",
    level: "N5",
    timings: t11,
  },
  {
    id: "12",
    sentence: "てを あらって、ごはんを ___。",
    options: ["たべます", "たべて", "たべた", "たべない"],
    answer: "たべます",
    answerIndex: 0,
    explanation: "「〜て、〜」表示動作的先後順序。",
    point: "〜て（動作連接）",
    level: "N5",
    timings: t12,
  },
  {
    id: "13",
    sentence: "すみません、ちょっと まって___。",
    options: ["ください", "います", "います", "みます"],
    answer: "ください",
    answerIndex: 0,
    explanation: "「〜てください」是禮貌的請求，",
    point: "〜てください（請求）",
    level: "N5",
    timings: t13,
  },
  {
    id: "14",
    sentence: "きょうは てんきが ___です。",
    options: ["いい", "よく", "よかった", "よくない"],
    answer: "いい",
    answerIndex: 0,
    explanation: "「いい」是「好」的意思，是い形容詞的特殊形。",
    point: "い形容詞（現在肯定）",
    level: "N5",
    timings: t14,
  },
  {
    id: "15",
    sentence: "きのうは さむ___です。",
    options: ["い", "かった", "くない", "くて"],
    answer: "かった",
    answerIndex: 1,
    explanation: "い形容詞的過去形：去掉「い」加「かった」。",
    point: "い形容詞（過去形）",
    level: "N5",
    timings: t15,
  },
  {
    id: "16",
    sentence: "にほんに ___です。",
    options: ["いきたい", "いきます", "いった", "いって"],
    answer: "いきたい",
    answerIndex: 0,
    explanation: "「〜たい」接在動詞ます形去掉ます後，",
    point: "〜たい（願望）",
    level: "N4",
    timings: t16,
  },
  {
    id: "17",
    sentence: "かれは いま でんわを ___。",
    options: ["しています", "します", "しました", "して"],
    answer: "しています",
    answerIndex: 0,
    explanation: "「〜ています」表示動作正在進行中，",
    point: "〜ています（進行形）",
    level: "N4",
    timings: t17,
  },
  {
    id: "18",
    sentence: "あめが ふっている___、でかけません。",
    options: ["から", "けど", "が", "ので"],
    answer: "から",
    answerIndex: 0,
    explanation: "「〜から」表示原因或理由，",
    point: "〜から（原因）",
    level: "N4",
    timings: t18,
  },
  {
    id: "19",
    sentence: "たかくて___、かいます。",
    options: ["も", "から", "が", "けど"],
    answer: "も",
    answerIndex: 0,
    explanation: "「〜ても」表示讓步，",
    point: "〜ても（讓步）",
    level: "N4",
    timings: t19,
  },
  {
    id: "20",
    sentence: "ここで タバコを すって___。",
    options: ["はいけません", "はいけない", "もいいですか", "もいい"],
    answer: "はいけません",
    answerIndex: 0,
    explanation: "「〜てはいけません」是禁止句型，表示「不可以做某事」。",
    point: "〜てはいけません（禁止）",
    level: "N4",
    timings: t20,
  },
  {
    id: "21",
    sentence: "しゃしんを とって___か？",
    options: ["もいいです", "はいけません", "ください", "います"],
    answer: "もいいです",
    answerIndex: 0,
    explanation: "「〜てもいいですか」是詢問許可的句型，",
    point: "〜てもいいですか（許可）",
    level: "N4",
    timings: t21,
  },
  {
    id: "22",
    sentence: "まいにち れんしゅう___なりません。",
    options: ["しなければ", "しなくて", "しないで", "しなかった"],
    answer: "しなければ",
    answerIndex: 0,
    explanation: "「〜なければなりません」表示義務，",
    point: "〜なければなりません（義務）",
    level: "N4",
    timings: t22,
  },
  {
    id: "23",
    sentence: "にほんに いった___があります。",
    options: ["こと", "もの", "とき", "ため"],
    answer: "こと",
    answerIndex: 0,
    explanation: "「〜たことがある」表示過去的經驗，",
    point: "〜たことがある（經驗）",
    level: "N4",
    timings: t23,
  },
  {
    id: "24",
    sentence: "かれは くるの___おもいます。",
    options: ["だと", "をと", "がと", "には"],
    answer: "だと",
    answerIndex: 0,
    explanation: "「〜と思います」表示個人的看法或推測，",
    point: "〜と思います（推測・意見）",
    level: "N4",
    timings: t24,
  },
  {
    id: "25",
    sentence: "しゅくだいを する___、ねます。",
    options: ["まえに", "あとで", "から", "ながら"],
    answer: "まえに",
    answerIndex: 0,
    explanation: "「〜前に」表示在做某事之前先做另一件事。",
    point: "〜前に（之前）",
    level: "N4",
    timings: t25,
  },
  {
    id: "26",
    sentence: "ごはんを たべた___、さんぽします。",
    options: ["あとで", "まえに", "から", "ながら"],
    answer: "あとで",
    answerIndex: 0,
    explanation: "「〜た後で」表示做完某事之後再做另一件事。",
    point: "〜た後で（之後）",
    level: "N4",
    timings: t26,
  },
  {
    id: "27",
    sentence: "あした あめが ふる___。",
    options: ["でしょう", "ました", "ません", "ください"],
    answer: "でしょう",
    answerIndex: 0,
    explanation: "「〜でしょう」表示推測，",
    point: "〜でしょう（推測）",
    level: "N4",
    timings: t27,
  },
  {
    id: "28",
    sentence: "このケーキは おいし___。",
    options: ["そうです", "らしいです", "はずです", "わけです"],
    answer: "そうです",
    answerIndex: 0,
    explanation: "「〜そうだ」（様態）接在形容詞語幹後，",
    point: "〜そうです（様態）",
    level: "N4",
    timings: t28,
  },
  {
    id: "29",
    sentence: "さいふに 500えん___ありません。",
    options: ["しか", "だけ", "ばかり", "まで"],
    answer: "しか",
    answerIndex: 0,
    explanation: "「〜しか〜ない」表示「只有〜（不夠）」，",
    point: "〜しか〜ない（限定・遺憾）",
    level: "N4",
    timings: t29,
  },
  {
    id: "30",
    sentence: "財布を家に忘れて_____。",
    options: ["しまいました", "みました", "あげました", "おきました"],
    answer: "しまいました",
    answerIndex: 0,
    explanation: "〜てしまう 表示某動作已完成，且帶有遺憾、失敗或不小心的語感。",
    point: "〜てしまう（完了・遺憾）",
    level: "N4",
    timings: t30,
  },
  {
    id: "31",
    sentence: "この部屋は何か変な匂いが_____。",
    options: ["します", "あります", "います", "なります"],
    answer: "します",
    answerIndex: 0,
    explanation: "〜がする 用於感覺類名詞（匂い・音・味・気持ち等），表示「感覺到〜」。",
    point: "〜がする（感覺）",
    level: "N4",
    timings: t31,
  },
  {
    id: "32",
    sentence: "犯人は警察に_____ました。",
    options: ["つかまれ", "つかまられ", "つかませ", "つかまさせ"],
    answer: "つかまられ",
    answerIndex: 1,
    explanation: "〜られる 受身形，表示被動「被〜」。",
    point: "〜られる（受身）",
    level: "N4",
    timings: t32,
  },
];
