// AUTO-GENERATED by scripts/gen_quiz_data.py — do not edit by hand.
// Source: ../../data/grammar.ts (app grammar question bank).
export type QuizTimings = { answer: number };

export type QuizItem = {
  id: string;
  sentence: string;
  options: string[];
  answer: string;
  answerIndex: number;
  explanation: string;
  point: string;
  level: string;
  timings?: QuizTimings;
};

import t01 from "./timings/01.json";
import t02 from "./timings/02.json";
import t03 from "./timings/03.json";
import t04 from "./timings/04.json";
import t05 from "./timings/05.json";
import t06 from "./timings/06.json";
import t07 from "./timings/07.json";
import t08 from "./timings/08.json";
import t09 from "./timings/09.json";
import t10 from "./timings/10.json";

export const quizItems: QuizItem[] = [
  {
    id: "01",
    sentence: "わたし___がくせいです。",
    options: ["は", "が", "を", "に"],
    answer: "は",
    answerIndex: 0,
    explanation: "「は」是主題助詞，用來提示句子的主題。",
    point: "は（主題助詞）",
    level: "N5",
    timings: t01,
  },
  {
    id: "02",
    sentence: "あそこに ねこ___います。",
    options: ["は", "が", "を", "で"],
    answer: "が",
    answerIndex: 1,
    explanation: "「が」用來強調主語，特別是描述存在（います／あります）時使用。",
    point: "が（主語助詞）",
    level: "N5",
    timings: t02,
  },
  {
    id: "03",
    sentence: "まいあさ コーヒー___のみます。",
    options: ["は", "が", "を", "に"],
    answer: "を",
    answerIndex: 2,
    explanation: "「を」是受詞助詞，接在動作的對象（受詞）後面。",
    point: "を（受詞助詞）",
    level: "N5",
    timings: t03,
  },
  {
    id: "04",
    sentence: "えいご___べんきょうしています。",
    options: ["は", "が", "を", "で"],
    answer: "を",
    answerIndex: 2,
    explanation: "「勉強する」是他動詞，學習的科目要用「を」。",
    point: "を（受詞助詞）",
    level: "N5",
    timings: t04,
  },
  {
    id: "05",
    sentence: "がっこう___いきます。",
    options: ["を", "が", "に", "で"],
    answer: "に",
    answerIndex: 2,
    explanation: "「に」表示移動的目的地。",
    point: "に（方向・目的地）",
    level: "N5",
    timings: t05,
  },
  {
    id: "06",
    sentence: "つくえの うえ___ほんが あります。",
    options: ["に", "で", "を", "が"],
    answer: "に",
    answerIndex: 0,
    explanation: "「に」也表示物品存在的位置。",
    point: "に（存在場所）",
    level: "N5",
    timings: t06,
  },
  {
    id: "07",
    sentence: "としょかん___べんきょうします。",
    options: ["に", "で", "を", "が"],
    answer: "で",
    answerIndex: 1,
    explanation: "「で」表示動作發生的場所。",
    point: "で（動作場所）",
    level: "N5",
    timings: t07,
  },
  {
    id: "08",
    sentence: "でんしゃ___かいしゃに いきます。",
    options: ["に", "で", "を", "は"],
    answer: "で",
    answerIndex: 1,
    explanation: "「で」也表示使用的交通工具或手段。",
    point: "で（手段・方法）",
    level: "N5",
    timings: t08,
  },
  {
    id: "09",
    sentence: "きのう えいが を ___。",
    options: ["みます", "みました", "みて", "みない"],
    answer: "みました",
    answerIndex: 1,
    explanation: "「〜ました」是禮貌形過去式。",
    point: "〜ました（過去形）",
    level: "N5",
    timings: t09,
  },
  {
    id: "10",
    sentence: "わたしは さかな___たべません。",
    options: ["を", "が", "は", "に"],
    answer: "は",
    answerIndex: 2,
    explanation: "否定句中，「〜は〜ません」的「は」有對比的語感，",
    point: "〜は〜ません（對比否定）",
    level: "N5",
    timings: t10,
  },
];
